site_name: KingdomsX
site_url: https://wiki.kingdomsx.com/
theme:
  name: material

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - nl2br
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
