name: MkDocs

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-

      - run: pip install properdocs pymdown-extensions properdocs-theme-mkdocs mkdocs-literate-nav

      - name: Clone Wiki
        run: git clone "https://github.com/CryptoMorin/KingdomsX.wiki.git" wiki

      - name: Populate docs folder
        run: bash scripts/populate_docs.sh

      - name: Convert GitHub formats to MkDocs formats (e.g. admonitions and backslashes)
        run: python scripts/github_to_mkdocs.py

      - name: Clean Sidebar
        run: python scripts/clean_sidebar.py docs/_Sidebar.md docs/_Sidebar.md

      - name: "MkDocs"
        run: mkdocs gh-deploy --force
        # run: properdocs gh-deploy --force -f mkdocs.yml
